services:
  - type: web
    name: api-prediccion-coche
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.main:app --host 0.0.0.0 --port 10000"
    plan: free
    envVars:
      - key: PORT
        value: 10000
